import type { Config } from 'tailwindcss';

const config: Config = {
	content: ['./app/**/*.{js,jsx,ts,tsx,html}'],
	theme: {
		extend: {
			colors: {
				background: 'var(--color-background)',
				overlay: 'var(--color-overlay)',
				surface: 'var(--color-surface)',
				transparent: 'var(--color-transparent)',
				panel: {
					solid: 'var(--color-panel-solid)',
					translucent: 'var(--color-panel-translucent)',
					DEFAULT: 'var(--color-panel)',
				},
				gray: {
					1: 'var(--gray-1)',
					2: 'var(--gray-2)',
					3: 'var(--gray-3)',
					4: 'var(--gray-4)',
					5: 'var(--gray-5)',
					6: 'var(--gray-6)',
					7: 'var(--gray-7)',
					8: 'var(--gray-8)',
					9: 'var(--gray-9)',
					10: 'var(--gray-10)',
					11: 'var(--gray-11)',
					12: 'var(--gray-12)',
					a1: 'var(--gray-a1)',
					a2: 'var(--gray-a2)',
					a3: 'var(--gray-a3)',
					a4: 'var(--gray-a4)',
					a5: 'var(--gray-a5)',
					a6: 'var(--gray-a6)',
					a7: 'var(--gray-a7)',
					a8: 'var(--gray-a8)',
					a9: 'var(--gray-a9)',
					a10: 'var(--gray-a10)',
					a11: 'var(--gray-a11)',
					a12: 'var(--gray-a12)',
					contrast: 'var(--gray-contrast)',
					surface: 'var(--gray-surface)',
					indicator: 'var(--gray-indicator)',
					track: 'var(--gray-track)',
					DEFAULT: 'var(--gray-9)',
				},
				accent: {
					1: 'var(--accent-1)',
					2: 'var(--accent-2)',
					3: 'var(--accent-3)',
					4: 'var(--accent-4)',
					5: 'var(--accent-5)',
					6: 'var(--accent-6)',
					7: 'var(--accent-7)',
					8: 'var(--accent-8)',
					9: 'var(--accent-9)',
					10: 'var(--accent-10)',
					11: 'var(--accent-11)',
					12: 'var(--accent-12)',
					a1: 'var(--accent-a1)',
					a2: 'var(--accent-a2)',
					a3: 'var(--accent-a3)',
					a4: 'var(--accent-a4)',
					a5: 'var(--accent-a5)',
					a6: 'var(--accent-a6)',
					a7: 'var(--accent-a7)',
					a8: 'var(--accent-a8)',
					a9: 'var(--accent-a9)',
					a10: 'var(--accent-a10)',
					a11: 'var(--accent-a11)',
					a12: 'var(--accent-a12)',
					contrast: 'var(--accent-contrast)',
					surface: 'var(--accent-surface)',
					indicator: 'var(--accent-indicator)',
					track: 'var(--accent-track)',
					DEFAULT: 'var(--accent-9)',
				},
				focus: {
					1: 'var(--focus-1)',
					2: 'var(--focus-2)',
					3: 'var(--focus-3)',
					4: 'var(--focus-4)',
					5: 'var(--focus-5)',
					6: 'var(--focus-6)',
					7: 'var(--focus-7)',
					8: 'var(--focus-8)',
					9: 'var(--focus-9)',
					10: 'var(--focus-10)',
					11: 'var(--focus-11)',
					12: 'var(--focus-12)',
					a1: 'var(--focus-a1)',
					a2: 'var(--focus-a2)',
					a3: 'var(--focus-a3)',
					a4: 'var(--focus-a4)',
					a5: 'var(--focus-a5)',
					a6: 'var(--focus-a6)',
					a7: 'var(--focus-a7)',
					a8: 'var(--focus-a8)',
					a9: 'var(--focus-a9)',
					a10: 'var(--focus-a10)',
					a11: 'var(--focus-a11)',
					a12: 'var(--focus-a12)',
					DEFAULT: 'var(--focus-9)',
				},
			},
			spacing: {
				1: 'var(--space-1)',
				2: 'var(--space-2)',
				3: 'var(--space-3)',
				4: 'var(--space-4)',
				5: 'var(--space-5)',
				6: 'var(--space-6)',
				7: 'var(--space-7)',
				8: 'var(--space-8)',
				9: 'var(--space-9)',
			},
			borderRadius: {
				1: 'var(--radius-1)',
				2: 'var(--radius-2)',
				3: 'var(--radius-3)',
				4: 'var(--radius-4)',
				5: 'var(--radius-5)',
				6: 'var(--radius-6)',
				full: 'var(--radius-full)',
				thumb: 'var(--radius-thumb)',
			},
			boxShadow: {
				1: 'var(--shadow-1)',
				2: 'var(--shadow-2)',
				3: 'var(--shadow-3)',
				4: 'var(--shadow-4)',
				5: 'var(--shadow-5)',
				6: 'var(--shadow-6)',
			},
		},
	},
	corePlugins: {
		preflight: false,
	},
};

export default config;
