import { defineSlotRecipe } from '@/app/styles/define-recipe';

export const commandRecipe = defineSlotRecipe({
  className: 'command',
  slots: [
    'root',
    'inputWrapper',
    'input',
    'list',
    'item',
    'group',
    'separator',
    'loading',
    'empty',
    'shortcut',
  ],
  base: {
    root: {
      display: 'flex',
      flexDirection: 'column',
      boxSize: 'full',
      overflow: 'hidden',
      borderRadius: 'md',
      backgroundColor: 'float',
      color: 'primary',
    },
    inputWrapper: {
      display: 'flex',
      height: '9',
      alignItems: 'center',
      paddingInline: '3',
      gap: '2',
      borderBlockEndWidth: '1px',
      borderBlockEndColor: 'border',
      _childIcon: {
        boxSize: '4',
        flexShrink: '0',
        color: 'muted',
      },
    },
    input: {
      minWidth: '0',
      flex: '1',
      backgroundColor: 'transparent',
      paddingBlock: '2',
      textStyle: 'sm',
      color: 'primary',
      outline: 'none',
      _placeholder: {
        color: 'muted',
      },
      _disabled: {
        opacity: '50%',
        cursor: 'not-allowed',
        pointerEvents: 'none',
      },
    },
    list: {
      maxHeight: '80',
      scrollPaddingBlock: '1',
      overflowX: 'hidden',
      overflowY: 'auto',
    },
    loading: {
      paddingBlock: '1.5',
      paddingInline: '2',
      textAlign: 'center',
      display: 'grid',
      placeItems: 'center',
      textStyle: 'sm',
      color: 'muted',
    },
    empty: {
      paddingBlock: '6',
      textAlign: 'center',
      display: 'grid',
      placeItems: 'center',
      textStyle: 'sm',
      color: 'muted',
    },
    group: {
      overflow: 'hidden',
      color: 'primary',
      padding: '1',
      '& :where([cmdk-group-heading])': {
        paddingInline: '2',
        paddingBlock: '1.5',
        textStyle: 'xs',
        fontWeight: 'medium',
        color: 'secondary',
      },
    },
    separator: {
      height: 'px',
      marginInline: '-1',
      backgroundColor: 'divider',
    },
    item: {
      position: 'relative',
      display: 'flex',
      cursor: 'default',
      alignItems: 'center',
      gap: '2',
      borderRadius: 'sm',
      paddingBlock: '1.5',
      paddingInline: '2',
      textStyle: 'sm',
      outlineStyle: 'none',
      userSelect: 'none',
      _disabled: {
        pointerEvents: 'none',
        opacity: '50%',
      },
      _selected: {
        backgroundColor: 'splash',
        color: 'display',
      },
      _childIcon: {
        pointerEvents: 'none',
        flexShrink: '0',
        boxSize: '4',
        color: 'symbol',
      },
    },
    shortcut: {
      marginInlineStart: 'auto',
      textStyle: 'xs',
      fontFamily: 'mono',
      letterSpacing: '0.1ch',
      color: 'symbol',
    },
  },
});
